name: Mixed actions
on: [workflow_dispatch]
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
  verified-action:
    runs-on: ubuntu-latest
    steps:
      - name: install dapr
        uses: dapr/setup-dapr@v1
        with:
          version: 1.2.0 # default is 1.2.0
          id: install
  non-verified-action:
    runs-on: ubuntu-latest
    steps:
    - name: Close issues
      uses: mxie/close-outdated-issues-action@main    # replace `main` with release tag
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  
