name: new-workflow
on: [push,workflow_dispatch]

jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: hej 
        run: echo hello world
      - name: Dump GitHub context
        run: echo '${{ toJSON(runner)}}'
