name: new-workflow
on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hej 
        run: echo hello world
      - name: Dump GitHub context
        run: echo '${{ toJSON(runner)}}'
